### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fowlis**
fix grammar error

### CODE REVIEW

**Comment by fowlis** [comment]
no idea how to do the whole signing thing (yet) but its just one character change

**Comment by SrS2225a** [comment]
Hello, thanks for making the MR. Signing your commits is easy enough. All you need to do is follow the listed instructions here: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification

I highly recommend getting this fixed asap as it verifys that commits are coming from you and not a bad actor.

Please let me know once you fix the commit with signing and I will accept it asap

**Comment by fowlis** [comment]
I managed to get the signing thing working I think, you can check [this commit ](https://github.com/fowlis/fowlis.github.io/commit/71ef8ce589feae5e1db80566a6a85afe8317efad) I just made
How can I re-commit the change I made and submit it again?

**Comment by SrS2225a** [comment]
That's great! Now, you won't have to worry about any commits being rejected,  as they will now always be signed. 
 
1. Here are the steps you can follow to re-add the commit:
 
2. Make sure that you are on the branch where the blocked commit is located.
 
3. Use the command `git log` to find the commit hash of the blocked commit.
 
4. Use the command `git rebase -i <hash-of-parent-commit>` to start an interactive rebase. This will open the default text editor and show a list of commits in the branch.
 
5. Locate the blocked commit in the list and change the word "pick" to "edit"
 
6. Save and close the file.
 
7. Use the command 1git commit --amend --gpg-sign` and enter the commit message to amend the commit. This will add the signing information to the commit and create a new commit hash
 
8. Use the command `git rebase --continue` to continue the rebase process
 
9. Once the rebase process is complete, you can push the updated branch to your remote repository with the command `git push --force-with-lease <remote-name> <branch-name>`
 
This will update the branch in the remote repository, and the merge request will include the signed commit.

**Comment by fowlis** [comment]
Cheers, I'll give it a shot tomorrow. I appreciate the clear guide 👍

**Comment by fowlis** [comment]
Think I did it right, how does this look now?

**Comment by SrS2225a** [comment]
Looks great! There are no conflicts with the base branch. It has been merged 👍

**Pull request merged**
